# Generated by Django 5.2.1 on 2025-05-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='appointments_notification',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='marketing_email',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='results_notification',
        ),
        migrations.AddField(
            model_name='settings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=10),
        ),
    ]
