# Generated by Django 5.2.1 on 2025-05-29 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_level_record_gameaudio_levelinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/speaking_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_stutter', models.FloatField(default=0.0)),
                ('prolongation', models.FloatField(default=0.0)),
                ('repetition', models.FloatField(default=0.0)),
                ('block', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
